CREATE TABLE worker
(
    ID       IDENTITY PRIMARY KEY,
    NAME     VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) >= 2),
    BIRTHDAY DATE CHECK (BIRTHDAY > '1900-12-31'),
    LEVEL    VARCHAR(20) NOT NULL CHECK LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior'),
    SALARY   INT CHECK (Salary >= 100 AND Salary <= 100000)
    );

CREATE TABLE client
(
    ID   INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) >= 2)
    );

CREATE TABLE  project
(
    ID          INT PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID   INT,
    START_DATE  date,
    FINISH_DATE date,
    FOREIGN KEY (CLIENT_ID) REFERENCES client (ID)
    );

CREATE TABLE  project_worker
(
    PROJECT_ID INT,
    WORKER_ID  INT,
    PRIMARY KEY (PROJECT_ID, WORKER_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES project (ID),
    FOREIGN KEY (WORKER_ID) REFERENCES worker (ID)
    );